### ISSUE TITLE
Support url references

### ISSUE THREAD

**Issue by Aerilius** [sitepoint/prmd-json-schema#1]
As for my understanding, references can refer to the current document, a path to a file or a url.

> $ref can also be a relative or absolute URI

(https://spacetelescope.github.io/understanding-json-schema/structuring.html)

When loading a json schema that refers to other schemas at remote urls, prmd cannot yet resolve or dereference them.

```
$ prmd verify my_schema.schema.json
…/json_schema-0.17.0/lib/json_pointer/evaluator.rb:24:in `evaluate': Path must begin with a leading "/": #https://www.somedomain.com/referenced_schema.schema.json. (ArgumentError)
        from …/json_schema-0.17.0/lib/json_schema/reference_expander.rb:142:in `resolve_pointer'
        from …/json_schema-0.17.0/lib/json_schema/reference_expander.rb:207:in `resolve_reference'
        from …/gems/json_schema-0.17.0/lib/json_schema/reference_expander.rb:97:in `dereference'
…
```

```
$ prmd doc verify my_schema.schema.json
Failed to dereference `https://www.somedomain.com/referenced_schema.schema.json`
Failed to dereference `#/definitions/some_data_type`
…/prmd-0.13.0/lib/prmd/schema.rb:96:in `block in dereference': undefined method `[]' for nil:NilClass (NoMethodError)
        from …/prmd-0.13.0/lib/prmd/schema.rb:95:in `each'
        from …/prmd-0.13.0/lib/prmd/schema.rb:95:in `dereference'
        from …/prmd-0.13.0/lib/prmd/schema.rb:100:in `dereference'
…
```

**Comment by Aerilius** [comment]
Sorry, wrong tab/wrong project.
